using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GetValuesFromColumn
{
    public static class EQRMSRawColumns
    {
        public static readonly Dictionary<string, int> ProcessedColumnNameAsKey = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
        {
            #region 200 lines dictionary
            {  "Position Id" ,  0   },
            {  "Expiry",   1   },
            {  "Compound Position Id", 2   },
            {  "Cusip <v2.0>", 3   },
            {  "Component Mnem <RIC>", 4   },
            {  "Strike",   5   },
            {  "Package Number <COM2>",    6   },
            {  "Security Type",    7   },
            {  "SecTypeId",    8   },
            {  "P/C",  9   },
            {  "Security Currency",    10  },
            {  "Model Name T-2",   11  },
            {  "Account",  12  },
            {  "Account Entity Code",  13  },
            {  "Calculating MMult",    14  },
            {  "Underlying Price T-2 <Position>",  15  },
            {  "Underlying Price T-1 <Position>",  16  },
            {  "Calculating MMult Spot",   17  },
            {  "PV01ScalingFactorT1",  18  },
            {  "Cash Delta T-1",   19  },
            {  "Gamma /1% T-2 <USD>",  20  },
            {  "Vega /1% T-2 <USD>",   21  },
            {  "PV01 /bp T-2 <USD>",   22  },
            {  "CR01 T-2 <USD>",   23  },
            {  "Cash Delta T-2",   24  },
            {  "Unit PV01 /bp T-1",    25  },
            {  "Unit PV01 /bp T-2",    26  },
            {  "PV01 /bp T-1 <DFX>",   27  },
            {  "PV01 /bp T-2 <DFX>",   28  },
            {  "Delta T-1 <DFX>",  29  },
            {  "Delta T-2 <USD>",  30  },
            {  "Delta T-2 <DFX>",  31  },
            {  "MMult",    32  },
            {  "MMultSpot",    33  },
            {  "Fair Value T-2 <USD>", 34  },
            {  "COB Price T-1",    35  },
            {  "Fair Price T-1",   36  },
            {  "Fair Price T-2",   37  },
            {  "Quantity T-1", 38  },
            {  "Quantity T-2", 39  },
            {  "Fair Value T-1 <DFX>", 40  },
            {  "Fair Value T-2 <DFX>", 41  },
            {  "Quantity for PAA", 42  },
            {  "Quantity for Spot",    43  },
            {  "External Source",  44  },
            {  "Trade Quantity",   45  },
            {  "KO Trades",    46  },
            {  "RiskPAA: Delta PL",    47  },
            {  "RiskPAA: Gamma PL",    48  },
            {  "RiskPAA: FX Delta PL", 49  },
            {  "FXDelta(TradeCcyAdj)", 50  },
            {  "FXDelta(DTDSAdj)", 51  },
            {  "RiskPAA: ASAS PL", 52  },
            {  "RiskPAA: ASFX PL", 53  },
            {  "RiskPAA: Rate PL", 54  },
            {  "RiskPAA: IR Vol PL",   55  },
            {  "RiskPAA: Volatility PL",   56  },
            {  "RiskPAA: VolGeo Unds PL",  57  },
            {  "VolGeoSWParams",   58  },
            {  "Risk PAA: VolThetaAdj",    59  },
            {  "RiskPAA: BorrowCostPL",    60  },
            {  "RiskPAA: Dividend PL", 61  },
            {  "RiskPAA: CrossGammaPL",    62  },
            {  "RiskPAA: VarSwap", 63  },
            {  "RiskPAA: VG VolAtm",   64  },
            {  "RiskPAA: VG Skew", 65  },
            {  "RiskPAA: VG Smile",    66  },
            {  "RiskPAA: VG CallWingA",    67  },
            {  "RiskPAA: VG CallWingB",    68  },
            {  "RiskPAA: VG PutWingA", 69  },
            {  "RiskPAA: VG PutWingB", 70  },
            {  "RiskPAA: VG RefForward",   71  },
            {  "New Trades",   72  },
            {  "Day Trading",  73  },
            {  "Upsize / Downsize",    74  },
            {  "Intraday Trading P&L", 75  },
            {  "P&L FX /USD T-2",  76  },
            {  "P&L FX /USD T-1",  77  },
            {  "Terminated Trades",    78  },
            {  "Total Risk PAA",   79  },
            {  "Total Risk PAA1",  80  },
            {  "Dividend PL (DTD T-1) <USD>",  81  },
            {  "Commission PL (DTD T-1) <USD>",    82  },
            {  "Interest PL (DTD T-1) <USD>",  83  },
            {  "Dividend PL (DTD T-1) <USD> Duped",    84  },
            {  "Coupon PL (DTD T-1) <USD>",    85  },
            {  "Extraordinary PL (DTD T-1) <USD>", 86  },
            {  "Net Accrued Interest (DTD T-1) <USD>", 87  },
            {  "Non Model PL", 88  },
            {  "Fair-Vs-Mkt Diff", 89  },
            {  "Fair-Vs-Mkt Diff 1",   90  },
            {  "Credit PAA",   91  },
            {  "Security Change PAA",  92  },
            {  "Carry| Theta", 93  },
            {  "Security Change PAA*", 94  },
            {  "Theta",    95  },
            {  "FXAdjustment", 96  },
            {  "Intraday Trading PL (DTD T-1) <USD> <PAA Style>",  97  },
            {  "Intraday Trading PL USD",  98  },
            {  "Intraday Trading PL (DTD T-1) <USD> <Trader Style>",   99  },
            {  "KOModels1",    100 },
            {  "KOModels2",    101 },
            {  "IsKOEvent",    102 },
            {  "KO Multiplier",    103 },
            {  "CheckKOFlag",  104 },
            {  "Generic Data <KnockedThrough>",    105 },
            {  "Generic Data <inOrOut>",   106 },
            {  "KO PL",    107 },
            {  "Total PAA1",   108 },
            {  "Total PAA",    109 },
            {  "Fair Economic (DTD T-1) <USD>",    110 },
            {  "Fair Economic (MTD T-2) <PFX>",    111 },
            {  "Fair Economic (DTDS T-1) <USD>",   112 },
            {  "Residual", 113 },
            {  "Security FX /USD T-1", 114 },
            {  "Sec FX /USD [-1]", 115 },
            {  "Model Name T-1",   116 },
            {  "%Residual",    117 },
            {  "Risk PAA: Sub Id T-1", 118 },
            {  "Factor Stress: Theta PL T-1 <USD>",    119 },
            {  "Risk PAA: Correlation PL T-1 <USD>",   120 },
            {  "Risk PAA: FX Correlation PL T-1 <USD>",    121 },
            {  "Risk PAA: Delta PL T-1 <USD>", 122 },
            {  "Risk PAA: Gamma PL T-1 <USD>", 123 },
            {  "Risk PAA: FX Delta PL T-1 <USD>",  124 },
            {  "Risk PAA: Rate PL T-1 <USD>",  125 },
            {  "Risk PAA: IR Vol PL T-1 <USD>",    126 },
            {  "Risk PAA: Borrow Cost PL T-1 <USD>",   127 },
            {  "Risk PAA: Dividend PL T-1 <USD>",  128 },
            {  "Risk PAA: Equity Vega PL T-1 <USD>",   129 },
            {  "Risk PAA: Skew Vega PL T-1 <USD>", 130 },
            {  "Risk PAA: Cross Gamma PL T-1 <USD>",   131 },
            {  "Risk PAA: VaR Swap Basis PL T-1 <USD>",    132 },
            {  "Risk PAA: Theta Vol Adjustment T-1 <USD>", 133 },
            {  "Risk PAA: Theta PL T-1 <USD>", 134 },
            {  "Risk PAA: VolGeo Vol Atm PL T-1 <USD>",    135 },
            {  "Risk PAA: VolGeo Skew PL T-1 <USD>",   136 },
            {  "Risk PAA: VolGeo Smile PL T-1 <USD>",  137 },
            {  "Risk PAA: VolGeo Put Wing A PL T-1 <USD>", 138 },
            {  "Risk PAA: VolGeo Call Wing A PL T-1 <USD>",    139 },
            {  "Risk PAA: VolGeo Put Wing B PL T-1 <USD>", 140 },
            {  "Risk PAA: VolGeo Call Wing B PL T-1 <USD>",    141 },
            {  "Risk PAA: VolGeo Ref Forward PL T-1 <USD>",    142 },
            {  "Risk PAA: VolGeo Put Slope TW PL T-1 <USD>",   143 },
            {  "Risk PAA: VolGeo Call Slope TW PL T-1 <USD>",  144 },
            {  "Risk PAA: VolGeo Put Convexity TW PL T-1 <USD>",   145 },
            {  "Risk PAA: VolGeo Call Convexity TW PL T-1 <USD>",  146 },
            {  "Risk PAA: TPlus Stress Missing T-1",   147 },
            {  "Factor Stress: Sub Id T-1",    148 },
            {  "Factor Stress: Prior Fair T-1 <USD>",  149 },
            {  "Factor Stress: Prior Fair Recalc T-1 <USD>",   150 },
            {  "Factor Stress: Fair T-1 <USD>",    151 },
            {  "stressError",  152 },
            {  "Stressing Errors", 153 },
            {  "IsVIXModel",   154 },
            {  "IsVIXModels1", 155 },
            {  "IsVIXModels2", 156 },
            {  "IsVanillaModel",   157 },
            {  "Fair Value T-1 <USD>", 158 },
            {  "Active Trade", 159 },
            {  "Fair Value T-2 <USD> Duped",   160 },
            {  "Final Counterparty",   161 },
            {  "IsTodayPastModels",    162 },
            {  "Multiplier T-1",   163 },
            {  "Security Class",   164 },
            {  "WarrantMultiplier",    165 },
            {  "HasTplusData", 166 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <Distribution>",  167 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <Reset>", 168 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <TransactionFee>",    169 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <BorrowCost>",    170 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <Distribution>",    171 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <Reset>",   172 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <TransactionFee>",  173 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <BorrowCost>",  174 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <Interest>",    175 },
            {  "PFS Realised CF Sudden DTD Total T-1 <USD>",   176 },
            {  "PFS Unrealised CF Sudden Total T-1 <USD>", 177 },
            {  "PFS RCF DTD Total T-1 <USD>",  178 },
            {  "Underlying FX /USD T-2",   179 },
            {  "Underlying FX /USD T-1",   180 },
            {  "Average Cost T-2", 181 },
            {  "Average Cost T-1", 182 },
            {  "Underlying Type",  183 },
            {  "IsPfsCBFut",   184 },
            {  "DeltaAdj", 185 },
            {  "EqFV USD[-1]", 186 },
            {  "EqFV USD[-2]", 187 },
            {  "NoUndPriceOnT-1",  188 },
            {  "NoUndPriceOnT-2",  189 },
            {  "PfsCfAdj1",    190 },
            {  "PfsCfAdj2",    191 },
            {  "PfsCfAdj3",    192 },
            {  "PfsCfAdj4",    193 },
            {  "PfsSecChngAdj",    194 },
            {  "PfsCfAdj", 195 },
            {  "DeltaDiff",    196 },
            {  "IsLargeResidual",  197 },
            {  "MissingDeltaPL",   198 },
            {  "WrongDeltaPL", 199 },
            {  "IsTerminated", 200 },
            {  "Outstanding Payments", 201 },
            {  "Outstanding Payments T-1 <Equity Leg>",    202 },
            {  "Outstanding Payments T-1 <Dividend Leg>",  203 },
            {  "Outstanding Payments T-1 <Libor Leg>", 204 },
            {  "Security Id",  205 },
            {  "RiskPAA: VG PutSlopeTW",   206 },
            {  "RiskPAA: VG PutConvexityTW",   207 },
            {  "RiskPAA: VG CallSlopeTW",  208 },
            {  "RiskPAA: VG CallConvexityTW",  209 },
            {  "IsTerminatedWithZeroFairValue",    210 },
            {  "volGeoError",  211 },
            {  "Vol Geo Stress Errors",    212 },
            {  "Exchange Fees PL (DTD T-1) <USD>", 213 },
            {  "Other Fees PL (DTD T-1) <USD>",    214 },
            {  "PFS Unrealised CF Total T-1 <USD>",    215 },
            {  "PFS Unrealised CF Total T-2 <USD>",    216 },
            {  "PFS Inconsistency Code T-1", 217 },
            {  "PFS Inconsistency Code T-2", 218 },
            {  "PFS Inconsistency Description T-1", 219},
            {  "PFS Inconsistency Description T-2", 220 },
            {  "DuplicateColumnDump", 221 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <Reserves>", 222 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <Interest>", 223 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <Reserves>", 224 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Interest>", 225 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <BorrowCost>", 226 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Reset>", 227 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <TransactionFee>", 228 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Distribution>", 229 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Reserves>", 230 },
            {  "PFS Realised CF Sudden DTD Amount T-1 <USD> <CompoundInterest>", 231 },
            {  "PFS Unrealised CF DTD Amount T-1 <USD> <CompoundInterest>", 232 },
            {  "PFS Realised CF DTD Amount T-1 <USD> <CompoundInterest>", 233 },
            {  "RiskPAA: Rate PL*", 234 }, //APAC ONLY
            {  "Underlying Currency", 235 },
            {  "Risk PAA: VolGeo Unds PL", 236 }, //APAC ONLY
            {  "Account Entity", 237 }, //APAC ONLY
            {  "Factor Stress: Rate PL T-1 <USD>", 238 },
            {  "Has Dividends", 239 },//APAC NAM ONLY
            {  "Underlying Id", 240 },//APAC ONLY
            {  "DivLookup", 241 },//APAC NAM ONLY
            {  "DividendToday", 242  },//APAC NAM ONLY
            {  "RiskPAA:  VG PutWingA", 243 }, //NAM error column
            {  "Total Risk PAA 1", 244 }, // NAM ERROR COLUMN
            {   "Derivative Series", 245 }, //NAM ONLY COLUMN
            #endregion
        };

        public static readonly Dictionary<int, string> ProcessedColumnIntAsKey = new Dictionary<int, string>()
        {
            #region 200 lines dictionary
            {  0    ,  "Position Id" }, 
            {  1    ,  "Expiry" },
            {  2    ,  "Compound Position Id" },
            {  3    ,  "Cusip <v2.0>" },
            {  4    ,  "Component Mnem <RIC>" },
            {  5    ,  "Strike" },
            {  6    ,  "Package Number <COM2>" },
            {  7    ,  "Security Type" },
            {  8    ,  "SecTypeId" },
            {  9    ,  "P/C" },
            {  10   ,  "Security Currency" },
            {  11   ,  "Model Name T-2" },
            {  12   ,  "Account" },
            {  13   ,  "Account Entity Code" },
            {  14   ,  "Calculating MMult" },
            {  15   ,  "Underlying Price T-2 <Position>" },
            {  16   ,  "Underlying Price T-1 <Position>" },
            {  17   ,  "Calculating MMult Spot" },
            {  18   ,  "PV01ScalingFactorT1" },
            {  19   ,  "Cash Delta T-1" },
            {  20   ,  "Gamma /1% T-2 <USD>" },
            {  21   ,  "Vega /1% T-2 <USD>" },
            {  22   ,  "PV01 /bp T-2 <USD>" },
            {  23   ,  "CR01 T-2 <USD>" },
            {  24   ,  "Cash Delta T-2" },
            {  25   ,  "Unit PV01 /bp T-1" },
            {  26   ,  "Unit PV01 /bp T-2" },
            {  27   ,  "PV01 /bp T-1 <DFX>" },
            {  28   ,  "PV01 /bp T-2 <DFX>" },
            {  29   ,  "Delta T-1 <DFX>" },
            {  30   ,  "Delta T-2 <USD>" },
            {  31   ,  "Delta T-2 <DFX>" },
            {  32   ,  "MMult" },
            {  33   ,  "MMultSpot" },
            {  34   ,  "Fair Value T-2 <USD>" },
            {  35   ,  "COB Price T-1" },
            {  36   ,  "Fair Price T-1" },
            {  37   ,  "Fair Price T-2" },
            {  38   ,  "Quantity T-1" },
            {  39   ,  "Quantity T-2" },
            {  40   ,  "Fair Value T-1 <DFX>" },
            {  41   ,  "Fair Value T-2 <DFX>" },
            {  42   ,  "Quantity for PAA" },
            {  43   ,  "Quantity for Spot" },
            {  44   ,  "External Source" },
            {  45   ,  "Trade Quantity" },
            {  46   ,  "KO Trades" },
            {  47   ,  "RiskPAA: Delta PL" },
            {  48   ,  "RiskPAA: Gamma PL" },
            {  49   ,  "RiskPAA: FX Delta PL" },
            {  50   ,  "FXDelta(TradeCcyAdj)" },
            {  51   ,  "FXDelta(DTDSAdj)" },
            {  52   ,  "RiskPAA: ASAS PL" },
            {  53   ,  "RiskPAA: ASFX PL" },
            {  54   ,  "RiskPAA: Rate PL" },
            {  55   ,  "RiskPAA: IR Vol PL" },
            {  56   ,  "RiskPAA: Volatility PL" },
            {  57   ,  "RiskPAA: VolGeo Unds PL" },
            {  58   ,  "VolGeoSWParams" },
            {  59   ,  "Risk PAA: VolThetaAdj" },
            {  60   ,  "RiskPAA: BorrowCostPL" },
            {  61   ,  "RiskPAA: Dividend PL" },
            {  62   ,  "RiskPAA: CrossGammaPL" },
            {  63   ,  "RiskPAA: VarSwap" },
            {  64   ,  "RiskPAA: VG VolAtm" },
            {  65   ,  "RiskPAA: VG Skew" },
            {  66   ,  "RiskPAA: VG Smile" },
            {  67   ,  "RiskPAA: VG CallWingA" },
            {  68   ,  "RiskPAA: VG CallWingB" },
            {  69   ,  "RiskPAA: VG PutWingA" },
            {  70   ,  "RiskPAA: VG PutWingB" },
            {  71   ,  "RiskPAA: VG RefForward" },
            {  72   ,  "New Trades" },
            {  73   ,  "Day Trading" },
            {  74   ,  "Upsize / Downsize" },
            {  75   ,  "Intraday Trading P&L" },
            {  76   ,  "P&L FX /USD T-2" },
            {  77   ,  "P&L FX /USD T-1" },
            {  78   ,  "Terminated Trades" },
            {  79   ,  "Total Risk PAA" },
            {  80   ,  "Total Risk PAA1" },
            {  81   ,  "Dividend PL (DTD T-1) <USD>" },
            {  82   ,  "Commission PL (DTD T-1) <USD>" },
            {  83   ,  "Interest PL (DTD T-1) <USD>" },
            {  84   ,  "Dividend PL (DTD T-1) <USD> Duped" },
            {  85   ,  "Coupon PL (DTD T-1) <USD>" },
            {  86   ,  "Extraordinary PL (DTD T-1) <USD>" },
            {  87   ,  "Net Accrued Interest (DTD T-1) <USD>" },
            {  88   ,  "Non Model PL" },
            {  89   ,  "Fair-Vs-Mkt Diff" },
            {  90   ,  "Fair-Vs-Mkt Diff 1" },
            {  91   ,  "Credit PAA" },
            {  92   ,  "Security Change PAA" },
            {  93   ,  "Carry| Theta" },
            {  94   ,  "Security Change PAA*" },
            {  95   ,  "Theta" },
            {  96   ,  "FXAdjustment" },
            {  97   ,  "Intraday Trading PL (DTD T-1) <USD> <PAA Style>" },
            {  98   ,  "Intraday Trading PL USD" },
            {  99   ,  "Intraday Trading PL (DTD T-1) <USD> <Trader Style>" },
            {  100  ,  "KOModels1" },
            {  101  ,  "KOModels2" },
            {  102  ,  "IsKOEvent" },
            {  103  ,  "KO Multiplier" },
            {  104  ,  "CheckKOFlag" },
            {  105  ,  "Generic Data <KnockedThrough>" },
            {  106  ,  "Generic Data <inOrOut>" },
            {  107  ,  "KO PL" },
            {  108  ,  "Total PAA1" },
            {  109  ,  "Total PAA" },
            {  110  ,  "Fair Economic (DTD T-1) <USD>" },
            {  111  ,  "Fair Economic (MTD T-2) <PFX>" },
            {  112  ,  "Fair Economic (DTDS T-1) <USD>" },
            {  113  ,  "Residual" },
            {  114  ,  "Security FX /USD T-1" },
            {  115  ,  "Sec FX /USD [-1]" },
            {  116  ,  "Model Name T-1" },
            {  117  ,  "%Residual" },
            {  118  ,  "Risk PAA: Sub Id T-1" },
            {  119  ,  "Factor Stress: Theta PL T-1 <USD>" },
            {  120  ,  "Risk PAA: Correlation PL T-1 <USD>" },
            {  121  ,  "Risk PAA: FX Correlation PL T-1 <USD>" },
            {  122  ,  "Risk PAA: Delta PL T-1 <USD>" },
            {  123  ,  "Risk PAA: Gamma PL T-1 <USD>" },
            {  124  ,  "Risk PAA: FX Delta PL T-1 <USD>" },
            {  125  ,  "Risk PAA: Rate PL T-1 <USD>" },
            {  126  ,  "Risk PAA: IR Vol PL T-1 <USD>" },
            {  127  ,  "Risk PAA: Borrow Cost PL T-1 <USD>" },
            {  128  ,  "Risk PAA: Dividend PL T-1 <USD>" },
            {  129  ,  "Risk PAA: Equity Vega PL T-1 <USD>" },
            {  130  ,  "Risk PAA: Skew Vega PL T-1 <USD>" },
            {  131  ,  "Risk PAA: Cross Gamma PL T-1 <USD>" },
            {  132  ,  "Risk PAA: VaR Swap Basis PL T-1 <USD>" },
            {  133  ,  "Risk PAA: Theta Vol Adjustment T-1 <USD>" },
            {  134  ,  "Risk PAA: Theta PL T-1 <USD>" },
            {  135  ,  "Risk PAA: VolGeo Vol Atm PL T-1 <USD>" },
            {  136  ,  "Risk PAA: VolGeo Skew PL T-1 <USD>" },
            {  137  ,  "Risk PAA: VolGeo Smile PL T-1 <USD>" },
            {  138  ,  "Risk PAA: VolGeo Put Wing A PL T-1 <USD>" },
            {  139  ,  "Risk PAA: VolGeo Call Wing A PL T-1 <USD>" },
            {  140  ,  "Risk PAA: VolGeo Put Wing B PL T-1 <USD>" },
            {  141  ,  "Risk PAA: VolGeo Call Wing B PL T-1 <USD>" },
            {  142  ,  "Risk PAA: VolGeo Ref Forward PL T-1 <USD>" },
            {  143  ,  "Risk PAA: VolGeo Put Slope TW PL T-1 <USD>" },
            {  144  ,  "Risk PAA: VolGeo Call Slope TW PL T-1 <USD>" },
            {  145  ,  "Risk PAA: VolGeo Put Convexity TW PL T-1 <USD>" },
            {  146  ,  "Risk PAA: VolGeo Call Convexity TW PL T-1 <USD>" },
            {  147  ,  "Risk PAA: TPlus Stress Missing T-1" },
            {  148  ,  "Factor Stress: Sub Id T-1" },
            {  149  ,  "Factor Stress: Prior Fair T-1 <USD>" },
            {  150  ,  "Factor Stress: Prior Fair Recalc T-1 <USD>" },
            {  151  ,  "Factor Stress: Fair T-1 <USD>" },
            {  152  ,  "stressError" },
            {  153  ,  "Stressing Errors" },
            {  154  ,  "IsVIXModel" },
            {  155  ,  "IsVIXModels1" },
            {  156  ,  "IsVIXModels2" },
            {  157  ,  "IsVanillaModel" },
            {  158  ,  "Fair Value T-1 <USD>" },
            {  159  ,  "Active Trade" },
            {  160  ,  "Fair Value T-2 <USD> Duped" },
            {  161  ,  "Final Counterparty" },
            {  162  ,  "IsTodayPastModels" },
            {  163  ,  "Multiplier T-1" },
            {  164  ,  "Security Class" },
            {  165  ,  "WarrantMultiplier" },
            {  166  ,  "HasTplusData" },
            {  167  ,  "PFS Realised CF DTD Amount T-1 <USD> <Distribution>" },
            {  168  ,  "PFS Realised CF DTD Amount T-1 <USD> <Reset>" },
            {  169  ,  "PFS Realised CF DTD Amount T-1 <USD> <TransactionFee>" },
            {  170  ,  "PFS Realised CF DTD Amount T-1 <USD> <BorrowCost>" },
            {  171  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <Distribution>" },
            {  172  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <Reset>" },
            {  173  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <TransactionFee>" },
            {  174  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <BorrowCost>" },
            {  175  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <Interest>" },
            {  176  ,  "PFS Realised CF Sudden DTD Total T-1 <USD>" },
            {  177  ,  "PFS Unrealised CF Sudden Total T-1 <USD>" },
            {  178  ,  "PFS RCF DTD Total T-1 <USD>" },
            {  179  ,  "Underlying FX /USD T-2" },
            {  180  ,  "Underlying FX /USD T-1" },
            {  181  ,  "Average Cost T-2" },
            {  182  ,  "Average Cost T-1" },
            {  183  ,  "Underlying Type" },
            {  184  ,  "IsPfsCBFut" },
            {  185  ,  "DeltaAdj" },
            {  186  ,  "EqFV USD[-1]" },
            {  187  ,  "EqFV USD[-2]" },
            {  188  ,  "NoUndPriceOnT-1" },
            {  189  ,  "NoUndPriceOnT-2" },
            {  190  ,  "PfsCfAdj1" },
            {  191  ,  "PfsCfAdj2" },
            {  192  ,  "PfsCfAdj3" },
            {  193  ,  "PfsCfAdj4" },
            {  194  ,  "PfsSecChngAdj" },
            {  195  ,  "PfsCfAdj" },
            {  196  ,  "DeltaDiff" },
            {  197  ,  "IsLargeResidual" },
            {  198  ,  "MissingDeltaPL" },
            {  199  ,  "WrongDeltaPL" },
            {  200  ,  "IsTerminated" },
            {  201  ,  "Outstanding Payments" },
            {  202  ,  "Outstanding Payments T-1 <Equity Leg>" },
            {  203  ,  "Outstanding Payments T-1 <Dividend Leg>" },
            {  204  ,  "Outstanding Payments T-1 <Libor Leg>" },
            {  205  ,  "Security Id" },
            {  206  ,  "RiskPAA: VG PutSlopeTW" },
            {  207  ,  "RiskPAA: VG PutConvexityTW" },
            {  208  ,  "RiskPAA: VG CallSlopeTW" },
            {  209  ,  "RiskPAA: VG CallConvexityTW" },
            {  210  ,  "IsTerminatedWithZeroFairValue" },
            {  211  ,  "volGeoError" },
            {  212  ,  "Vol Geo Stress Errors" },
            {  213  ,  "Exchange Fees PL (DTD T-1) <USD>" },
            {  214  ,  "Other Fees PL (DTD T-1) <USD>" },
            {  215  ,  "PFS Unrealised CF Total T-1 <USD>" },
            {  216  ,  "PFS Unrealised CF Total T-2 <USD>" },
            {  217  ,  "PFS Inconsistency Code T-1" },
            {  218  ,  "PFS Inconsistency Code T-2" },
            {  219  ,  "PFS Inconsistency Description T-1" },
            {  220  ,  "PFS Inconsistency Description T-2" },
            {  221  ,  "DuplicateColumnDump" },
            {  222  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <Reserves>" },
            {  223  ,  "PFS Realised CF DTD Amount T-1 <USD> <Interest>" },
            {  224  ,  "PFS Realised CF DTD Amount T-1 <USD> <Reserves>" },
            {  225  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Interest>" },
            {  226  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <BorrowCost>" },
            {  227  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Reset>" },
            {  228  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <TransactionFee>" },
            {  229  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Distribution>"  },
            {  230  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <Reserves>" },
            {  231  ,  "PFS Realised CF Sudden DTD Amount T-1 <USD> <CompoundInterest>" },
            {  232  ,  "PFS Unrealised CF DTD Amount T-1 <USD> <CompoundInterest>" },
            {  233  ,  "PFS Realised CF DTD Amount T-1 <USD> <CompoundInterest>" },
            {  234  ,  "RiskPAA: Rate PL*" }, //APAC only
            {  235  ,  "Underlying Currency" },
            {  236  ,  "Risk PAA: VolGeo Unds PL" }, //RiskPAA: VolGeo Unds PL
            {  237  ,  "Account Entity" }, //APAC ONLY
            {  238  ,  "Factor Stress: Rate PL T-1 <USD>" }, //APAC ONLY
            {  239  ,  "Has Dividends" },//APAC ONLY
            {  240  ,  "Underlying Id" },//APAC ONLY
            {  241  ,  "DivLookup" },//APAC ONLY
            {  242  ,  "DividendToday" },//APAC ONLY
            {  243  ,  "RiskPAA:  VG PutWingA" }, //NAM ONLY; double space in column name
            {  244  ,  "Total Risk PAA 1"}, //NAM ONLY; space after PAA
            {  245  ,  "Derivative Series"}, //NAM ONLY COLUMN
            #endregion
        };

        public static readonly Dictionary<string, int> EQRMSMonths = new Dictionary<string, int>
        {
            { "Jan", 01 },
            { "Feb", 02 },
            { "Mar", 03 },
            { "Apr", 04 },
            { "May", 05 },
            { "Jun", 06 },
            { "Jul", 07 },
            { "Aug", 08 },
            { "Sep", 09 },
            { "Oct", 10 },
            { "Nov", 11 },
            { "Dec", 12 }
        };
    }
}
