using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Antlr4.Runtime;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

namespace AntlrEQrms
{
    public class Program : RecogniseFormulasBaseVisitor<string>
    {
        
        static void Main(string[] args)
        {
            string file =
                @"V:\ReportOutput\EMEA\May 2016 No hidden columns\RiskPAASummaryBeta214.20160527.DELTA_ONE+ED_STRATEGY_OTHER_NEW.txt";
            string line; 
            
            using (var sr = new StreamReader(file)) { line = sr.ReadLine(); }

            AntlrInputStream input = new AntlrInputStream(line);
            RecogniseFormulasLexer lexer = new RecogniseFormulasLexer(input);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            List<int> column = new List<int> {1, 4};
            RecogniseFormulasParser parser = new RecogniseFormulasParser(tokens, column);
            parser.file();
           
            Console.ReadKey();
        }


    public static readonly Dictionary<String, int> ProcessedColumnNameAsKey = new Dictionary<String, int>
    {
	    #region 200 lines dictionary
	    {  "Position Id",  0   },
         {  "Expiry",   1   },
         {  "Compound Position Id", 2   },
         {  "Cusip <v2.0>", 3   },
         {  "Component Mnem <RIC>", 4   },
         {  "Strike",   5   },
         {  "Package Number <COM2>",    6   },
         {  "Security Type",    7   },
         {  "SecTypeId",    8   },
         {  "P/C",  9   },
         {  "Security Currency",    10  },
         {  "Model Name T-2",   11  },
         {  "Account",  12  },
         {  "Account Entity Code",  13  },
         {  "Calculating MMult",    14  },
         {  "Underlying Price T-2 <Position>",  15  },
         {  "Underlying Price T-1 <Position>",  16  },
         {  "Calculating MMult Spot",   17  },
         {  "PV01ScalingFactorT1",  18  },
         {  "Cash Delta T-1",   19  },
         {  "Gamma /1% T-2 <USD>",  20  },
         {  "Vega /1% T-2 <USD>",   21  },
         {  "PV01 /bp T-2 <USD>",   22  },
         {  "CR01 T-2 <USD>",   23  },
         {  "Cash Delta T-2",   24  },
         {  "Unit PV01 /bp T-1",    25  },
         {  "Unit PV01 /bp T-2",    26  },
         {  "PV01 /bp T-1 <DFX>",   27  },
         {  "PV01 /bp T-2 <DFX>",   28  },
         {  "Delta T-1 <DFX>",  29  },
         {  "Delta T-2 <USD>",  30  },
         {  "Delta T-2 <DFX>",  31  },
         {  "MMult",    32  },
         {  "MMultSpot",    33  },
         {  "Fair Value T-2 <USD>", 34  },
         {  "COB Price T-1",    35  },
         {  "Fair Price T-1",   36  },
         {  "Fair Price T-2",   37  },
         {  "Quantity T-1", 38  },
         {  "Quantity T-2", 39  },
         {  "Fair Value T-1 <DFX>", 40  },
         {  "Fair Value T-2 <DFX>", 41  },
         {  "Quantity for PAA", 42  },
         {  "Quantity for Spot",    43  },
         {  "External Source",  44  },
         {  "Trade Quantity",   45  },
         {  "KO Trades",    46  },
         {  "RiskPAA: Delta PL",    47  },
         {  "RiskPAA: Gamma PL",    48  },
         {  "RiskPAA: FX Delta PL", 49  },
         {  "FXDelta(TradeCcyAdj)", 50  },
         {  "FXDelta(DTDSAdj)", 51  },
         {  "RiskPAA: ASAS PL", 52  },
         {  "RiskPAA: ASFX PL", 53  },
         {  "RiskPAA: Rate PL", 54  },
         {  "RiskPAA: IR Vol PL",   55  },
         {  "RiskPAA: Volatility PL",   56  },
         {  "RiskPAA: VolGeo Unds PL",  57  },
         {  "VolGeoSWParams",   58  },
         {  "Risk PAA: VolThetaAdj",    59  },
         {  "RiskPAA: BorrowCostPL",    60  },
         {  "RiskPAA: Dividend PL", 61  },
         {  "RiskPAA: CrossGammaPL",    62  },
         {  "RiskPAA: VarSwap", 63  },
         {  "RiskPAA: VG VolAtm",   64  },
         {  "RiskPAA: VG Skew", 65  },
         {  "RiskPAA: VG Smile",    66  },
         {  "RiskPAA: VG CallWingA",    67  },
         {  "RiskPAA: VG CallWingB",    68  },
         {  "RiskPAA: VG PutWingA", 69  },
         {  "RiskPAA: VG PutWingB", 70  },
         {  "RiskPAA: VG RefForward",   71  },
         {  "New Trades",   72  },
         {  "Day Trading",  73  },
         {  "Upsize / Downsize",    74  },
         {  "Intraday Trading P&L", 75  },
         {  "P&L FX /USD T-2",  76  },
         {  "P&L FX /USD T-1",  77  },
         {  "Terminated Trades",    78  },
         {  "Total Risk PAA",   79  },
         {  "Total Risk PAA1",  80  },
         {  "Dividend PL (DTD T-1) <USD>",  81  },
         {  "Commission PL (DTD T-1) <USD>",    82  },
         {  "Interest PL (DTD T-1) <USD>",  83  },
         {  "Dividend PL (DTD T-1) <USD> Duped",    84  },
         {  "Coupon PL (DTD T-1) <USD>",    85  },
         {  "Extraordinary PL (DTD T-1) <USD>", 86  },
         {  "Net Accrued Interest (DTD T-1) <USD>", 87  },
         {  "Non Model PL", 88  },
         {  "Fair-Vs-Mkt Diff", 89  },
         {  "Fair-Vs-Mkt Diff 1",   90  },
         {  "Credit PAA",   91  },
         {  "Security Change PAA",  92  },
         {  "Carry| Theta", 93  },
         {  "Security Change PAA*", 94  },
         {  "Theta",    95  },
         {  "FXAdjustment", 96  },
         {  "Intraday Trading PL (DTD T-1) <USD> <PAA Style>",  97  },
         {  "Intraday Trading PL USD",  98  },
         {  "Intraday Trading PL (DTD T-1) <USD> <Trader Style>",   99  },
         {  "KOModels1",    100 },
         {  "KOModels2",    101 },
         {  "IsKOEvent",    102 },
         {  "KO Multiplier",    103 },
         {  "CheckKOFlag",  104 },
         {  "Generic Data <KnockedThrough>",    105 },
         {  "Generic Data <inOrOut>",   106 },
         {  "KO PL",    107 },
         {  "Total PAA1",   108 },
         {  "Total PAA",    109 },
         {  "Fair Economic (DTD T-1) <USD>",    110 },
         {  "Fair Economic (MTD T-2) <PFX>",    111 },
         {  "Fair Economic (DTDS T-1) <USD>",   112 },
         {  "Residual", 113 },
         {  "Security FX /USD T-1", 114 },
         {  "Sec FX /USD [-1]", 115 },
         {  "Model Name T-1",   116 },
         {  "%Residual",    117 },
         {  "Risk PAA: Sub Id T-1", 118 },
         {  "Factor Stress: Theta PL T-1 <USD>",    119 },
         {  "Risk PAA: Correlation PL T-1 <USD>",   120 },
         {  "Risk PAA: FX Correlation PL T-1 <USD>",    121 },
         {  "Risk PAA: Delta PL T-1 <USD>", 122 },
         {  "Risk PAA: Gamma PL T-1 <USD>", 123 },
         {  "Risk PAA: FX Delta PL T-1 <USD>",  124 },
         {  "Risk PAA: Rate PL T-1 <USD>",  125 },
         {  "Risk PAA: IR Vol PL T-1 <USD>",    126 },
         {  "Risk PAA: Borrow Cost PL T-1 <USD>",   127 },
         {  "Risk PAA: Dividend PL T-1 <USD>",  128 },
         {  "Risk PAA: Equity Vega PL T-1 <USD>",   129 },
         {  "Risk PAA: Skew Vega PL T-1 <USD>", 130 },
         {  "Risk PAA: Cross Gamma PL T-1 <USD>",   131 },
         {  "Risk PAA: VaR Swap Basis PL T-1 <USD>",    132 },
         {  "Risk PAA: Theta Vol Adjustment T-1 <USD>", 133 },
         {  "Risk PAA: Theta PL T-1 <USD>", 134 },
         {  "Risk PAA: VolGeo Vol Atm PL T-1 <USD>",    135 },
         {  "Risk PAA: VolGeo Skew PL T-1 <USD>",   136 },
         {  "Risk PAA: VolGeo Smile PL T-1 <USD>",  137 },
         {  "Risk PAA: VolGeo Put Wing A PL T-1 <USD>", 138 },
         {  "Risk PAA: VolGeo Call Wing A PL T-1 <USD>",    139 },
         {  "Risk PAA: VolGeo Put Wing B PL T-1 <USD>", 140 },
         {  "Risk PAA: VolGeo Call Wing B PL T-1 <USD>",    141 },
         {  "Risk PAA: VolGeo Ref Forward PL T-1 <USD>",    142 },
         {  "Risk PAA: VolGeo Put Slope TW PL T-1 <USD>",   143 },
         {  "Risk PAA: VolGeo Call Slope TW PL T-1 <USD>",  144 },
         {  "Risk PAA: VolGeo Put Convexity TW PL T-1 <USD>",   145 },
         {  "Risk PAA: VolGeo Call Convexity TW PL T-1 <USD>",  146 },
         {  "Risk PAA: TPlus Stress Missing T-1",   147 },
         {  "Factor Stress: Sub Id T-1",    148 },
         {  "Factor Stress: Prior Fair T-1 <USD>",  149 },
         {  "Factor Stress: Prior Fair Recalc T-1 <USD>",   150 },
         {  "Factor Stress: Fair T-1 <USD>",    151 },
         {  "stressError",  152 },
         {  "Stressing Errors", 153 },
         {  "IsVIXModel",   154 },
         {  "IsVIXModels1", 155 },
         {  "IsVIXModels2", 156 },
         {  "IsVanillaModel",   157 },
         {  "Fair Value T-1 <USD>", 158 },
         {  "Active Trade", 159 },
         {  "Fair Value T-2 <USD> Duped",   160 },
         {  "Final Counterparty",   161 },
         {  "IsTodayPastModels",    162 },
         {  "Multiplier T-1",   163 },
         {  "Security Class",   164 },
         {  "WarrantMultiplier",    165 },
         {  "HasTplusData", 166 },
         {  "PFS Realised CF DTD Amount T-1 <USD> <Distribution>",  167 },
         {  "PFS Realised CF DTD Amount T-1 <USD> <Reset>", 168 },
         {  "PFS Realised CF DTD Amount T-1 <USD> <TransactionFee>",    169 },
         {  "PFS Realised CF DTD Amount T-1 <USD> <BorrowCost>",    170 },
         {  "PFS Unrealised CF DTD Amount T-1 <USD> <Distribution>",    171 },
         {  "PFS Unrealised CF DTD Amount T-1 <USD> <Reset>",   172 },
         {  "PFS Unrealised CF DTD Amount T-1 <USD> <TransactionFee>",  173 },
         {  "PFS Unrealised CF DTD Amount T-1 <USD> <BorrowCost>",  174 },
         {  "PFS Unrealised CF DTD Amount T-1 <USD> <Interest>",    175 },
         {  "PFS Realised CF Sudden DTD Total T-1 <USD>",   176 },
         {  "PFS Unrealised CF Sudden Total T-1 <USD>", 177 },
         {  "PFS RCF DTD Total T-1 <USD>",  178 },
         {  "Underlying FX /USD T-2",   179 },
         {  "Underlying FX /USD T-1",   180 },
         {  "Average Cost T-2", 181 },
         {  "Average Cost T-1", 182 },
         {  "Underlying Type",  183 },
         {  "IsPfsCBFut",   184 },
         {  "DeltaAdj", 185 },
         {  "EqFV USD[-1]", 186 },
         {  "EqFV USD[-2]", 187 },
         {  "NoUndPriceOnT-1",  188 },
         {  "NoUndPriceOnT-2",  189 },
         {  "PfsCfAdj1",    190 },
         {  "PfsCfAdj2",    191 },
         {  "PfsCfAdj3",    192 },
         {  "PfsCfAdj4",    193 },
         {  "PfsSecChngAdj",    194 },
         {  "PfsCfAdj", 195 },
         {  "DeltaDiff",    196 },
         {  "IsLargeResidual",  197 },
         {  "MissingDeltaPL",   198 },
         {  "WrongDeltaPL", 199 },
         {  "IsTerminated", 200 },
         {  "Outstanding Payments", 201 },
         {  "Outstanding Payments T-1 <Equity Leg>",    202 },
         {  "Outstanding Payments T-1 <Dividend Leg>",  203 },
         {  "Outstanding Payments T-1 <Libor Leg>", 204 },
         {  "Security Id",  205 },
         {  "RiskPAA: VG PutSlopeTW",   206 },
         {  "RiskPAA: VG PutConvexityTW",   207 },
         {  "RiskPAA: VG CallSlopeTW",  208 },
         {  "RiskPAA: VG CallConvexityTW",  209 },
         {  "IsTerminatedWithZeroFairValue",    210 },
         {  "volGeoError",  211 },
         {  "Vol Geo Stress Errors",    212 },
         {  "Exchange Fees PL (DTD T-1) <USD>", 213 },
         {  "Other Fees PL (DTD T-1) <USD>",    214 },
         {  "PFS Unrealised CF Total T-1 <USD>",    215 },
         {  "PFS Unrealised CF Total T-2 <USD>",    216 }
	    #endregion
    };
       
    }
}
